package home;

import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Allan
 * Frustei-me pra pegar a idade, porém FACIL :P
 * Não validei o RG, pois fiquei com preguicinha :D
 */
public class Home extends javax.swing.JFrame {
    PessoaTM PTM;
    NumberFormat dot = NumberFormat.getNumberInstance(Locale.GERMANY);
    
    
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        
        PTM = new PessoaTM();
        visu_tbl.setModel(PTM);
    }
    
    public void LIMPARCAD(){
        cad_c_nome.setText("");
        cad_c_endereco.setText("");
        cad_c_cidade.setText("");
        cad_c_telefone.setText("");
        cad_c_dtnasc.setText("");
        cad_c_peso.setText("");
        cad_c_altura.setText("");
        cad_c_cpf.setText("");
        cad_c_rg.setText("");
    }
    
    public void LIMPAREDI(){
        edi_c_nome.setText("");
        edi_c_endereco.setText("");
        edi_c_cidade.setText("");
        edi_c_telefone.setText("");
        edi_c_dtnasc.setText("");
        edi_c_peso.setText("");
        edi_c_altura.setText("");
        edi_c_cpf.setText("");
        edi_c_rg.setText("");
    }

    public void LIMPAREXC(){
        exc_c_nome.setText("");
        exc_c_cpf.setText("");
        exc_c_rg.setText("");
    }
    
    public String Format(String number){
        number = number.replace(",", ".");
        return number;
    }
   
    public void isEnable(boolean key){
        edi_c_nome.setEnabled(key);
        edi_c_endereco.setEnabled(key);
        edi_c_cidade.setEnabled(key);
        edi_c_telefone.setEnabled(key);
        edi_c_dtnasc.setEnabled(key);
        edi_c_peso.setEnabled(key);
        edi_c_altura.setEnabled(key);
        edi_c_cpf.setEnabled(key);
        edi_c_rg.setEnabled(key);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cad_btn_cancelar2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cad_t_nome = new javax.swing.JLabel();
        cad_c_nome = new javax.swing.JTextField();
        cad_t_endereco = new javax.swing.JLabel();
        cad_c_endereco = new javax.swing.JTextField();
        cad_t_cidade = new javax.swing.JLabel();
        cad_c_cidade = new javax.swing.JTextField();
        cad_t_telefone = new javax.swing.JLabel();
        cad_t_dtnasc = new javax.swing.JLabel();
        cad_t_peso = new javax.swing.JLabel();
        cad_t_altura = new javax.swing.JLabel();
        cad_t_cpf = new javax.swing.JLabel();
        cad_t_rg = new javax.swing.JLabel();
        cad_c_telefone = new javax.swing.JFormattedTextField();
        cad_c_dtnasc = new javax.swing.JFormattedTextField();
        cad_c_rg = new javax.swing.JFormattedTextField();
        cad_c_cpf = new javax.swing.JFormattedTextField();
        cad_c_peso = new javax.swing.JFormattedTextField();
        cad_c_altura = new javax.swing.JFormattedTextField();
        cad_btn_salvar = new javax.swing.JButton();
        cad_btn_cancelar = new javax.swing.JButton();
        cad_t_titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        visu_tbl = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        edi_t_nome = new javax.swing.JLabel();
        edi_c_nome = new javax.swing.JTextField();
        edi_t_telefone = new javax.swing.JLabel();
        edi_c_telefone = new javax.swing.JFormattedTextField();
        edi_t_dtnasc = new javax.swing.JLabel();
        edi_c_dtnasc = new javax.swing.JFormattedTextField();
        edi_t_peso = new javax.swing.JLabel();
        edi_c_peso = new javax.swing.JFormattedTextField();
        edi_t_altura = new javax.swing.JLabel();
        edi_c_altura = new javax.swing.JFormattedTextField();
        edi_t_endereco = new javax.swing.JLabel();
        edi_c_endereco = new javax.swing.JTextField();
        edi_t_cidade = new javax.swing.JLabel();
        edi_c_cidade = new javax.swing.JTextField();
        edi_t_cpf = new javax.swing.JLabel();
        edi_c_cpf = new javax.swing.JFormattedTextField();
        edi_t_rg = new javax.swing.JLabel();
        edi_c_rg = new javax.swing.JFormattedTextField();
        edi_btn_editar = new javax.swing.JButton();
        edi_btn_cancelar = new javax.swing.JButton();
        edi_btn_salvar = new javax.swing.JButton();
        edi_t_titulo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        exc_t_nome = new javax.swing.JLabel();
        exc_c_nome = new javax.swing.JTextField();
        exc_t_cpf = new javax.swing.JLabel();
        exc_c_cpf = new javax.swing.JFormattedTextField();
        exc_t_rg = new javax.swing.JLabel();
        exc_c_rg = new javax.swing.JFormattedTextField();
        exc_btn_excluir = new javax.swing.JButton();
        exc_btn_cancelar = new javax.swing.JButton();
        exc_t_titulo = new javax.swing.JLabel();

        cad_btn_cancelar2.setText("CANCELAR");
        cad_btn_cancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_btn_cancelar2ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("CADASTRO DE PESSOAS");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 337));

        cad_t_nome.setText("Nome:");

        cad_t_endereco.setText("Endereco:");

        cad_t_cidade.setText("Cidade:");

        cad_t_telefone.setText("Telefone:");

        cad_t_dtnasc.setText("Data Nascimento:");

        cad_t_peso.setText("Peso (KG):");

        cad_t_altura.setText("Altura:");

        cad_t_cpf.setText("CPF:");

        cad_t_rg.setText("RG:");

        try {
            cad_c_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            cad_c_dtnasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cad_c_dtnasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_c_dtnascActionPerformed(evt);
            }
        });

        try {
            cad_c_rg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            cad_c_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cad_c_peso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        cad_c_altura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        cad_btn_salvar.setText("CADASTRAR");
        cad_btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_btn_salvarActionPerformed(evt);
            }
        });

        cad_btn_cancelar.setText("CANCELAR");
        cad_btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_btn_cancelarActionPerformed(evt);
            }
        });

        cad_t_titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cad_t_titulo.setText("CADASTRO DE PESSOAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cad_btn_salvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cad_btn_cancelar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cad_t_telefone)
                    .addComponent(cad_t_dtnasc)
                    .addComponent(cad_t_peso)
                    .addComponent(cad_t_altura)
                    .addComponent(cad_t_nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cad_c_peso)
                    .addComponent(cad_c_telefone)
                    .addComponent(cad_c_dtnasc)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cad_c_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(cad_c_altura))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cad_t_endereco)
                    .addComponent(cad_t_cidade)
                    .addComponent(cad_t_cpf)
                    .addComponent(cad_t_rg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cad_c_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cad_c_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cad_c_endereco)
                    .addComponent(cad_c_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(cad_t_titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(cad_t_titulo)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cad_t_endereco)
                            .addComponent(cad_c_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cad_t_cidade)
                            .addComponent(cad_c_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cad_t_cpf)
                            .addComponent(cad_c_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cad_t_rg)
                            .addComponent(cad_c_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cad_t_nome)
                            .addComponent(cad_c_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cad_t_telefone)
                            .addComponent(cad_c_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cad_t_dtnasc)
                            .addComponent(cad_c_dtnasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cad_t_peso)
                            .addComponent(cad_c_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cad_t_altura)
                            .addComponent(cad_c_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cad_btn_salvar)
                    .addComponent(cad_btn_cancelar))
                .addContainerGap())
        );

        tabs.addTab("Cadastro", jPanel1);

        visu_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Endereço", "Cidade", "Telefone", "Data Nascimento", "Idade", "Peso", "Altura", "CPF", "RG"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        visu_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visu_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(visu_tbl);
        if (visu_tbl.getColumnModel().getColumnCount() > 0) {
            visu_tbl.getColumnModel().getColumn(0).setPreferredWidth(80);
            visu_tbl.getColumnModel().getColumn(1).setPreferredWidth(250);
            visu_tbl.getColumnModel().getColumn(2).setPreferredWidth(100);
            visu_tbl.getColumnModel().getColumn(3).setPreferredWidth(100);
            visu_tbl.getColumnModel().getColumn(4).setPreferredWidth(150);
            visu_tbl.getColumnModel().getColumn(6).setPreferredWidth(100);
            visu_tbl.getColumnModel().getColumn(7).setPreferredWidth(100);
            visu_tbl.getColumnModel().getColumn(8).setPreferredWidth(150);
            visu_tbl.getColumnModel().getColumn(9).setPreferredWidth(150);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
        );

        tabs.addTab("Visualização", jPanel2);

        edi_t_nome.setText("Nome:");

        edi_c_nome.setEnabled(false);
        edi_c_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi_c_nomeActionPerformed(evt);
            }
        });

        edi_t_telefone.setText("Telefone:");

        try {
            edi_c_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edi_c_telefone.setEnabled(false);

        edi_t_dtnasc.setText("Data Nascimento:");

        try {
            edi_c_dtnasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edi_c_dtnasc.setEnabled(false);
        edi_c_dtnasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi_c_dtnascActionPerformed(evt);
            }
        });

        edi_t_peso.setText("Peso (KG):");

        edi_c_peso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        edi_c_peso.setEnabled(false);

        edi_t_altura.setText("Altura:");

        edi_c_altura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        edi_c_altura.setEnabled(false);

        edi_t_endereco.setText("Endereco:");

        edi_c_endereco.setEnabled(false);

        edi_t_cidade.setText("Cidade:");

        edi_c_cidade.setEnabled(false);

        edi_t_cpf.setText("CPF:");

        try {
            edi_c_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edi_c_cpf.setEnabled(false);

        edi_t_rg.setText("RG:");

        try {
            edi_c_rg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edi_c_rg.setEnabled(false);

        edi_btn_editar.setText("EDITAR");
        edi_btn_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edi_btn_editarMouseClicked(evt);
            }
        });
        edi_btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi_btn_editarActionPerformed(evt);
            }
        });

        edi_btn_cancelar.setText("CANCELAR");
        edi_btn_cancelar.setEnabled(false);
        edi_btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi_btn_cancelarActionPerformed(evt);
            }
        });

        edi_btn_salvar.setText("SALVAR");
        edi_btn_salvar.setEnabled(false);
        edi_btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi_btn_salvarActionPerformed(evt);
            }
        });

        edi_t_titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        edi_t_titulo.setText("EDIÇÃO DE PESSOA SELECIONADA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edi_btn_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edi_btn_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edi_btn_cancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edi_t_telefone)
                            .addComponent(edi_t_dtnasc)
                            .addComponent(edi_t_peso)
                            .addComponent(edi_t_altura)
                            .addComponent(edi_t_nome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edi_c_telefone)
                                    .addComponent(edi_c_nome)
                                    .addComponent(edi_c_dtnasc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(edi_c_peso)
                                    .addComponent(edi_c_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(edi_t_endereco)
                                    .addComponent(edi_t_cidade)
                                    .addComponent(edi_t_cpf)
                                    .addComponent(edi_t_rg))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edi_c_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edi_c_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edi_c_endereco, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(edi_c_cidade)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(edi_t_titulo)))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(edi_t_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edi_t_nome)
                    .addComponent(edi_c_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edi_t_endereco)
                    .addComponent(edi_c_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edi_t_cidade)
                    .addComponent(edi_c_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edi_t_telefone)
                    .addComponent(edi_c_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edi_t_dtnasc)
                    .addComponent(edi_t_cpf)
                    .addComponent(edi_c_dtnasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edi_c_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edi_t_peso)
                    .addComponent(edi_t_rg)
                    .addComponent(edi_c_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edi_c_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edi_t_altura)
                    .addComponent(edi_c_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edi_btn_editar)
                    .addComponent(edi_btn_cancelar)
                    .addComponent(edi_btn_salvar))
                .addContainerGap())
        );

        tabs.addTab("Edição", jPanel3);

        exc_t_nome.setText("Nome:");

        exc_c_nome.setEnabled(false);

        exc_t_cpf.setText("CPF:");

        try {
            exc_c_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        exc_c_cpf.setEnabled(false);

        exc_t_rg.setText("RG:");

        try {
            exc_c_rg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        exc_c_rg.setEnabled(false);

        exc_btn_excluir.setText("EXCLUIR");
        exc_btn_excluir.setEnabled(false);
        exc_btn_excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exc_btn_excluirMouseClicked(evt);
            }
        });
        exc_btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exc_btn_excluirActionPerformed(evt);
            }
        });

        exc_btn_cancelar.setText("CANCELAR");
        exc_btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exc_btn_cancelarActionPerformed(evt);
            }
        });

        exc_t_titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exc_t_titulo.setText("EXCLUSÃO DE PESSOA SELECIONADA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(exc_t_rg)
                                    .addComponent(exc_t_cpf))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(exc_c_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exc_c_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(exc_t_nome)
                                .addGap(18, 18, 18)
                                .addComponent(exc_c_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(exc_btn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exc_btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(exc_t_titulo)
                        .addGap(0, 154, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(exc_t_titulo)
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exc_c_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exc_t_nome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exc_c_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exc_t_cpf))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exc_c_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exc_t_rg)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(exc_btn_excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exc_btn_cancelar)))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        tabs.addTab("Exclusão", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cad_c_dtnascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_c_dtnascActionPerformed
        LIMPARCAD();
        
        
    }//GEN-LAST:event_cad_c_dtnascActionPerformed

    private void cad_btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_btn_salvarActionPerformed
        CPF pf = new CPF(cad_c_cpf.getText());
        
        Data d = new Data(cad_c_dtnasc.getText()+" ",Data.BarraSemHora);
        Data Hoje = new Data();
        
        if(pf.isCPF()){
            if(Hoje.getTimestamp().getTime() > d.getTimestamp().getTime()){
                Pessoa p = new Pessoa();

                double peso = Double.parseDouble(Format(cad_c_peso.getText()));
                double altura = Double.parseDouble(Format(cad_c_altura.getText()));

                p.setNome(cad_c_nome.getText());
                p.setEndereco(cad_c_endereco.getText());
                p.setCidade(cad_c_cidade.getText());
                p.setTelefone(cad_c_telefone.getText());
                p.setDataNascimento(cad_c_dtnasc.getText());
                p.setPeso(peso);
                p.setAltura(altura);
                p.setCPF(cad_c_cpf.getText());
                p.setRG(cad_c_rg.getText());

                PTM.addPessoa(p);
                
                LIMPARCAD();
            }else{
                JOptionPane.showMessageDialog(rootPane,"DATA inválido!");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"CPF inválido!");
        }
    }//GEN-LAST:event_cad_btn_salvarActionPerformed

    private void cad_btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_btn_cancelarActionPerformed
        LIMPARCAD();
    }//GEN-LAST:event_cad_btn_cancelarActionPerformed

    private void visu_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visu_tblMouseClicked
        int i = visu_tbl.getSelectedRow();
        if(i>=0 && i<PTM.getRowCount()){
            Pessoa p = PTM.getPessoa(i);
            
            // <editor-fold defaultstate="collapsed" desc="EDIÇÃO">
            edi_c_nome.setText(p.getNome());
            edi_c_endereco.setText(p.getEndereco());
            edi_c_cidade.setText(p.getCidade());
            edi_c_telefone.setText(p.getTelefone());
            edi_c_dtnasc.setText(p.getDataNascimento());
            edi_c_peso.setText(String.valueOf(p.getPeso()));
            edi_c_altura.setText(String.valueOf(p.getAltura()));
            edi_c_cpf.setText(p.getCPF());
            edi_c_rg.setText(p.getRG());
            // </editor-fold>
            
            // <editor-fold defaultstate="collapsed" desc="EXCLUSÃO">
            exc_c_nome.setText(p.getNome());
            exc_c_cpf.setText(p.getCPF());
            exc_c_rg.setText(p.getRG());
            
            exc_btn_excluir.setEnabled(true);
            // </editor-fold>
        }
            
    }//GEN-LAST:event_visu_tblMouseClicked

    private void edi_c_dtnascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi_c_dtnascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edi_c_dtnascActionPerformed

    private void edi_btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi_btn_editarActionPerformed
        isEnable(true);
        
        edi_btn_salvar.setEnabled(true);
        edi_btn_cancelar.setEnabled(true);
        edi_btn_editar.setEnabled(false);
    }//GEN-LAST:event_edi_btn_editarActionPerformed

    private void edi_btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi_btn_cancelarActionPerformed
        LIMPAREDI();
        isEnable(false);
        
        edi_btn_salvar.setEnabled(false);
        edi_btn_cancelar.setEnabled(false);
        edi_btn_editar.setEnabled(true);
    }//GEN-LAST:event_edi_btn_cancelarActionPerformed

    private void cad_btn_cancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_btn_cancelar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cad_btn_cancelar2ActionPerformed

    private void edi_btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi_btn_salvarActionPerformed
        int i = visu_tbl.getSelectedRow();
        CPF pf = new CPF(cad_c_cpf.getText());
        
        Data d = new Data(edi_c_dtnasc.getText()+" ",Data.BarraSemHora);
        Data Hoje = new Data();
        
        if(pf.isCPF()){
            if(Hoje.getTimestamp().getTime() > d.getTimestamp().getTime()){
                PTM.getPessoa(i).setNome(edi_c_nome.getText());
                PTM.getPessoa(i).setEndereco(edi_c_endereco.getText());
                PTM.getPessoa(i).setCidade(edi_c_cidade.getText());
                PTM.getPessoa(i).setTelefone(edi_c_telefone.getText());
                PTM.getPessoa(i).setDataNascimento(edi_c_dtnasc.getText());
                PTM.getPessoa(i).setPeso(Double.parseDouble(Format(edi_c_peso.getText())));
                PTM.getPessoa(i).setAltura(Double.parseDouble(Format(edi_c_altura.getText())));
                PTM.getPessoa(i).setCPF(edi_c_cpf.getText());
                PTM.getPessoa(i).setRG(edi_c_rg.getText());
            }else{
            JOptionPane.showMessageDialog(rootPane,"DATA inválido!");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"CPF inválido!");
        }
        
        
        
        LIMPAREDI();
        LIMPAREXC();
        isEnable(false);
        edi_btn_salvar.setEnabled(false);
        edi_btn_cancelar.setEnabled(false);
        edi_btn_editar.setEnabled(true);
    }//GEN-LAST:event_edi_btn_salvarActionPerformed

    private void edi_btn_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edi_btn_editarMouseClicked
        
    }//GEN-LAST:event_edi_btn_editarMouseClicked

    private void exc_btn_excluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exc_btn_excluirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exc_btn_excluirMouseClicked

    private void exc_btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exc_btn_excluirActionPerformed
        int i = visu_tbl.getSelectedRow();
        if(i>=0 && i<PTM.getRowCount()){
            PTM.remove(i);
            LIMPAREDI();
            LIMPAREXC();
        }
    }//GEN-LAST:event_exc_btn_excluirActionPerformed

    private void exc_btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exc_btn_cancelarActionPerformed
        LIMPAREXC();
        exc_btn_excluir.setEnabled(false);
    }//GEN-LAST:event_exc_btn_cancelarActionPerformed

    private void edi_c_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi_c_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edi_c_nomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cad_btn_cancelar;
    private javax.swing.JButton cad_btn_cancelar2;
    private javax.swing.JButton cad_btn_salvar;
    private javax.swing.JFormattedTextField cad_c_altura;
    private javax.swing.JTextField cad_c_cidade;
    private javax.swing.JFormattedTextField cad_c_cpf;
    private javax.swing.JFormattedTextField cad_c_dtnasc;
    private javax.swing.JTextField cad_c_endereco;
    private javax.swing.JTextField cad_c_nome;
    private javax.swing.JFormattedTextField cad_c_peso;
    private javax.swing.JFormattedTextField cad_c_rg;
    private javax.swing.JFormattedTextField cad_c_telefone;
    private javax.swing.JLabel cad_t_altura;
    private javax.swing.JLabel cad_t_cidade;
    private javax.swing.JLabel cad_t_cpf;
    private javax.swing.JLabel cad_t_dtnasc;
    private javax.swing.JLabel cad_t_endereco;
    private javax.swing.JLabel cad_t_nome;
    private javax.swing.JLabel cad_t_peso;
    private javax.swing.JLabel cad_t_rg;
    private javax.swing.JLabel cad_t_telefone;
    private javax.swing.JLabel cad_t_titulo;
    private javax.swing.JButton edi_btn_cancelar;
    private javax.swing.JButton edi_btn_editar;
    private javax.swing.JButton edi_btn_salvar;
    private javax.swing.JFormattedTextField edi_c_altura;
    private javax.swing.JTextField edi_c_cidade;
    private javax.swing.JFormattedTextField edi_c_cpf;
    private javax.swing.JFormattedTextField edi_c_dtnasc;
    private javax.swing.JTextField edi_c_endereco;
    private javax.swing.JTextField edi_c_nome;
    private javax.swing.JFormattedTextField edi_c_peso;
    private javax.swing.JFormattedTextField edi_c_rg;
    private javax.swing.JFormattedTextField edi_c_telefone;
    private javax.swing.JLabel edi_t_altura;
    private javax.swing.JLabel edi_t_cidade;
    private javax.swing.JLabel edi_t_cpf;
    private javax.swing.JLabel edi_t_dtnasc;
    private javax.swing.JLabel edi_t_endereco;
    private javax.swing.JLabel edi_t_nome;
    private javax.swing.JLabel edi_t_peso;
    private javax.swing.JLabel edi_t_rg;
    private javax.swing.JLabel edi_t_telefone;
    private javax.swing.JLabel edi_t_titulo;
    private javax.swing.JButton exc_btn_cancelar;
    private javax.swing.JButton exc_btn_excluir;
    private javax.swing.JFormattedTextField exc_c_cpf;
    private javax.swing.JTextField exc_c_nome;
    private javax.swing.JFormattedTextField exc_c_rg;
    private javax.swing.JLabel exc_t_cpf;
    private javax.swing.JLabel exc_t_nome;
    private javax.swing.JLabel exc_t_rg;
    private javax.swing.JLabel exc_t_titulo;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable visu_tbl;
    // End of variables declaration//GEN-END:variables
}
